apiVersion: secrets-store.csi.x-k8s.io/v1  # specifies the API version to use
kind: SecretProviderClass  # specifies the Kubernetes object type to create
metadata:
  name: eks-test-secret  # specifies the name for the object being created
spec:
  provider: aws  # specifies the provider for the object
  secretObjects:  
  - secretName: gradle-app-secrets  
    type: Opaque  # specifies the type of secret object to be created in Kubernetes
    data:  
    - objectName: database-url  # specifies the name of the object in the secret manager
      key: database-url  # specifies the key in the Kubernetes secret where the object should be mounted
    - objectName: db-user  
      key: db-user  
    - objectName: db-pass  
      key: db-pass  
  parameters:  # specifies the additional configuration parameters for the object
    objects: |  
        - objectName: "gradle-app-secrets"  
          objectType: "secretsmanager"  
          jmesPath:  
            - path: "database-url"  
              objectAlias: "database-url"  
            - path: "db-user"  
              objectAlias: "db-user"  
            - path: "db-pass"  
              objectAlias: "db-pass" 